// Schema for all 145 fields with grouping and types
// Each field has: id (dot-path), label, type: 'text' | 'number' | 'date' | 'textarea'

export const SCHEMA = [
  {
    group: 'Header Information',
    fields: [
      { id: 'header.vesselName', label: 'Vessel Name', type: 'text' },
      { id: 'header.manufacturedBy', label: 'Manufactured By (Mfg. By)', type: 'text' },
      { id: 'header.certificateNo', label: 'Certificate No.', type: 'text' },
      { id: 'header.ownerName', label: 'Owner Name', type: 'text' },
      { id: 'header.manufacturingDate', label: 'Manufacturing Date', type: 'date' },
      { id: 'header.dateOfService', label: 'Date of Service', type: 'date' },
      { id: 'header.imoNo', label: 'IMO No.', type: 'text' },
      { id: 'header.type', label: 'Type', type: 'text' },
      { id: 'header.nextServiceDue', label: 'Next Service Due', type: 'date' },
      { id: 'header.capacity', label: 'Capacity', type: 'text' },
      { id: 'header.liferaftSerialNo', label: 'Liferaft Serial No.', type: 'text' },
      { id: 'header.lastServiceDate', label: 'Last Service Date', type: 'date' },
    ],
  },
  {
    group: 'BUOYANCY – STATUS',
    fields: [
      { id: 'buoyancy.arches', label: 'Arches', type: 'text' },
      { id: 'buoyancy.boardingRampLadder', label: 'Boarding Ramp / Ladder', type: 'text' },
      { id: 'buoyancy.centreStrut', label: 'Centre Strut', type: 'text' },
      { id: 'buoyancy.inflateDeflateValve', label: 'Inflate / Deflate Valve', type: 'text' },
      { id: 'buoyancy.lifeline', label: 'Lifeline', type: 'text' },
      { id: 'buoyancy.lifelinePatch', label: 'Lifeline Patch', type: 'text' },
      { id: 'buoyancy.reliefValves', label: 'Relief Valves', type: 'text' },
      { id: 'buoyancy.towingBridleLine', label: 'Towing Bridle / Line', type: 'text' },
      { id: 'buoyancy.gasInflationValve', label: 'Gas Inflation Valve', type: 'text' },
    ],
  },
  {
    group: 'INFLATABLE EQUIPMENTS – STATUS',
    fields: [
      { id: 'inflatable.firingCable', label: 'Firing Cable', type: 'text' },
      { id: 'inflatable.conduit', label: 'Conduit', type: 'text' },
      { id: 'inflatable.operatingHandle', label: 'Operating Handle', type: 'text' },
      { id: 'inflatable.highPressureHose', label: 'High Pressure Hose', type: 'text' },
      { id: 'inflatable.tConnection', label: 'T. Connection', type: 'text' },
      { id: 'inflatable.deflationPlugKey', label: 'Deflation Plug Key', type: 'text' },
      { id: 'inflatable.container', label: 'Container', type: 'text' },
      { id: 'inflatable.labels', label: 'Labels', type: 'text' },
      { id: 'inflatable.painterPocketLines', label: 'Painter Pocket / Lines', type: 'text' },
      { id: 'inflatable.burstingBandsStraps', label: 'Bursting Bands / Straps', type: 'text' },
      { id: 'inflatable.sealingGaskets', label: 'Sealing Gaskets', type: 'text' },
      { id: 'inflatable.drainHoles', label: 'Drain Holes', type: 'text' },
      { id: 'inflatable.containerLining', label: 'Container Lining', type: 'text' },
      { id: 'inflatable.containerIdKit', label: 'Container ID Kit', type: 'text' },
    ],
  },
  {
    group: 'EQUIPMENTS – STATUS',
    fields: [
      { id: 'equipment.seaAnchorAndLines', label: 'Sea Anchor and Lines', type: 'text' },
      { id: 'equipment.torchCells', label: 'Torch Cells', type: 'text' },
      { id: 'equipment.torch', label: 'Torch', type: 'text' },
      { id: 'equipment.torchBulb', label: 'Torch Bulb', type: 'text' },
      { id: 'equipment.tinOpener', label: 'Tin Opener', type: 'text' },
      { id: 'equipment.whistle', label: 'Whistle', type: 'text' },
      { id: 'equipment.radarReflector', label: 'Radar Reflector', type: 'text' },
      { id: 'equipment.radarReflectorPatch', label: 'Radar Reflector Patch', type: 'text' },
      { id: 'equipment.emergencyEquipmentDrumValise', label: 'Emergency Equipment Drum / Valise', type: 'text' },
      { id: 'equipment.bailers', label: 'Bailer(s)', type: 'text' },
      { id: 'equipment.bungs', label: 'Bungs', type: 'text' },
      { id: 'equipment.bellow', label: 'Bellow', type: 'text' },
      { id: 'equipment.drinkingVessel', label: 'Drinking Vessel', type: 'text' },
      { id: 'equipment.fishingKit', label: 'Fishing Kit', type: 'text' },
      { id: 'equipment.heliograph', label: 'Heliograph', type: 'text' },
      { id: 'equipment.knife', label: 'Knife', type: 'text' },
      { id: 'equipment.leakStopper', label: 'Leak Stopper', type: 'text' },
      { id: 'equipment.paddles', label: 'Paddles', type: 'text' },
      { id: 'equipment.repairKit', label: 'Repair Kit', type: 'text' },
      { id: 'equipment.thermalProtectiveAids', label: 'Thermal Protective Aids', type: 'text' },
      { id: 'equipment.survivalManual', label: 'Survival Manual', type: 'text' },
      { id: 'equipment.signalingChart', label: 'Signaling Chart', type: 'text' },
      { id: 'equipment.seaSickBags', label: 'Sea Sick Bags', type: 'text' },
      { id: 'equipment.sponges', label: 'Sponges', type: 'text' },
      { id: 'equipment.scissors', label: 'Scissors', type: 'text' },
    ],
  },
  {
    group: 'Hand Flares',
    fields: [
      { id: 'handFlares.quantity', label: 'Hand Flares (Qty)', type: 'number' },
      { id: 'handFlares.expiry', label: 'Hand Flares Expiry', type: 'date' },
      { id: 'handFlares.lotNo', label: 'Hand Flares Lot No', type: 'text' },
      { id: 'handFlares.status', label: 'Hand Flares Status', type: 'text' },
      { id: 'handFlares.make', label: 'Hand Flares Make', type: 'text' },
    ],
  },
  {
    group: 'Parachute Signals',
    fields: [
      { id: 'parachuteSignals.quantity', label: 'Parachute Signals (Qty)', type: 'number' },
      { id: 'parachuteSignals.expiry', label: 'Parachute Signals Expiry', type: 'date' },
      { id: 'parachuteSignals.lotNo', label: 'Parachute Signals Lot No', type: 'text' },
      { id: 'parachuteSignals.status', label: 'Parachute Signals Status', type: 'text' },
      { id: 'parachuteSignals.make', label: 'Parachute Signals Make', type: 'text' },
    ],
  },
  {
    group: 'Smoke Floats',
    fields: [
      { id: 'smokeFloats.quantity', label: 'Smoke Floats (Qty)', type: 'number' },
      { id: 'smokeFloats.expiry', label: 'Smoke Floats Expiry', type: 'date' },
      { id: 'smokeFloats.lotNo', label: 'Smoke Floats Lot No', type: 'text' },
      { id: 'smokeFloats.status', label: 'Smoke Floats Status', type: 'text' },
      { id: 'smokeFloats.make', label: 'Smoke Floats Make', type: 'text' },
    ],
  },
  {
    group: 'CANOPY',
    fields: [
      { id: 'canopy.outerCanopy', label: 'Outer Canopy', type: 'text' },
      { id: 'canopy.innerCanopy', label: 'Inner Canopy', type: 'text' },
      { id: 'canopy.entranceFlap', label: 'Entrance Flap', type: 'text' },
      { id: 'canopy.rainCatchments', label: 'Rain Catchments', type: 'text' },
      { id: 'canopy.reflectorTape', label: 'Reflector Tape', type: 'text' },
      { id: 'canopy.viewingPort', label: 'Viewing Port', type: 'text' },
      { id: 'canopy.lightUnits', label: 'Light Units', type: 'text' },
    ],
  },
  {
    group: 'Sea Cells (Lithium)',
    fields: [
      { id: 'seaCells.make', label: 'Sea Cells Make', type: 'text' },
      { id: 'seaCells.expiry', label: 'Sea Cells Expiry', type: 'date' },
    ],
  },
  {
    group: 'Parachute Signals',
    fields: [
      { id: 'parachuteSignals.quantity', label: 'Parachute Signals (Qty)', type: 'number' },
      { id: 'parachuteSignals.expiry', label: 'Parachute Signals Expiry', type: 'date' },
      { id: 'parachuteSignals.lotNo', label: 'Parachute Signals Lot No', type: 'text' },
      { id: 'parachuteSignals.status', label: 'Parachute Signals Status', type: 'text' },
      { id: 'parachuteSignals.make', label: 'Parachute Signals Make', type: 'text' },
    ],
  },
  {
    group: 'Smoke Floats',
    fields: [
      { id: 'smokeFloats.quantity', label: 'Smoke Floats (Qty)', type: 'number' },
      { id: 'smokeFloats.expiry', label: 'Smoke Floats Expiry', type: 'date' },
      { id: 'smokeFloats.lotNo', label: 'Smoke Floats Lot No', type: 'text' },
      { id: 'smokeFloats.status', label: 'Smoke Floats Status', type: 'text' },
      { id: 'smokeFloats.make', label: 'Smoke Floats Make', type: 'text' },
    ],
  },
  {
    group: 'First Aid Kit',
    fields: [
      { id: 'firstAidKit.quantity', label: 'First Aid Kit (Qty)', type: 'number' },
      { id: 'firstAidKit.expiry', label: 'First Aid Kit Expiry', type: 'date' },
      { id: 'firstAidKit.lotNo', label: 'First Aid Kit Lot No', type: 'text' },
      { id: 'firstAidKit.status', label: 'First Aid Kit Status', type: 'text' },
      { id: 'firstAidKit.make', label: 'First Aid Kit Make', type: 'text' },
    ],
  },
  {
    group: 'FLOOR',
    fields: [
      { id: 'floor.outerFloor', label: 'Outer Floor', type: 'text' },
      { id: 'floor.innerFloor', label: 'Inner Floor', type: 'text' },
      { id: 'floor.inflateDeflateValve', label: 'Inflate / Deflate Valve', type: 'text' },
      { id: 'floor.aerialSupport', label: 'Aerial Support', type: 'text' },
      { id: 'floor.cylinderPocket', label: 'Cylinder Pocket', type: 'text' },
      { id: 'floor.waterPocket', label: 'Water Pocket', type: 'text' },
      { id: 'floor.ernPackTapes', label: 'Ern Pack Tapes', type: 'text' },
      { id: 'floor.rescueLine', label: 'Rescue Line', type: 'text' },
      { id: 'floor.rightingStrap', label: 'Righting Strap', type: 'text' },
      { id: 'floor.polytheneLiner', label: 'Polythene Liner', type: 'text' },
    ],
  },
  {
    group: 'Rations',
    fields: [
      { id: 'rations.quantity', label: 'Rations (Qty)', type: 'number' },
      { id: 'rations.expiry', label: 'Rations Expiry', type: 'date' },
      { id: 'rations.lotNo', label: 'Rations Lot No', type: 'text' },
      { id: 'rations.status', label: 'Rations Status', type: 'text' },
      { id: 'rations.make', label: 'Rations Make', type: 'text' },
    ],
  },
  {
    group: 'Water',
    fields: [
      { id: 'water.quantity', label: 'Water (Qty)', type: 'number' },
      { id: 'water.expiry', label: 'Water Expiry', type: 'date' },
      { id: 'water.lotNo', label: 'Water Lot No', type: 'text' },
      { id: 'water.status', label: 'Water Status', type: 'text' },
      { id: 'water.make', label: 'Water Make', type: 'text' },
    ],
  },
  {
    group: 'Anti-Seasickness Tablets',
    fields: [
      { id: 'antiSeasicknessTablets.quantity', label: 'Anti-Seasickness Tablets (Qty)', type: 'number' },
      { id: 'antiSeasicknessTablets.expiry', label: 'Anti-Seasickness Tablets Expiry', type: 'date' },
      { id: 'antiSeasicknessTablets.lotNo', label: 'Anti-Seasickness Tablets Lot No', type: 'text' },
      { id: 'antiSeasicknessTablets.status', label: 'Anti-Seasickness Tablets Status', type: 'text' },
      { id: 'antiSeasicknessTablets.make', label: 'Anti-Seasickness Tablets Make', type: 'text' },
    ],
  },
  {
    group: 'WORKING PRESSURE TEST',
    fields: [
      { id: 'workingPressureTest.startOn', label: 'Start On', type: 'text' },
      { id: 'workingPressureTest.pressureWaterInchesStart', label: 'Pressure Water (Inches) Start', type: 'number' },
      { id: 'workingPressureTest.timeOff', label: 'Time Off', type: 'text' },
      { id: 'workingPressureTest.pressureWaterInchesEnd', label: 'Pressure Water (Inches) End', type: 'number' },
      { id: 'workingPressureTest.valveResetInches', label: 'Valve Reset (Inches)', type: 'number' },
      { id: 'workingPressureTest.tests', label: 'Tests', type: 'textarea' },
      { id: 'workingPressureTest.remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  {
    group: 'LOWER BUOYANCY TEST',
    fields: [
      { id: 'lowerBuoyancyTest.startOn', label: 'Lower Buoyancy Start On', type: 'text' },
      { id: 'lowerBuoyancyTest.pressureWaterInches', label: 'Lower Buoyancy Pr. Water (Inches)', type: 'text' },
      { id: 'lowerBuoyancyTest.timeOff', label: 'Lower Buoyancy Time Off', type: 'text' },
      { id: 'lowerBuoyancyTest.pressureWaterInches2', label: 'Lower Buoyancy Pr. Water (Inches 2)', type: 'text' },
      { id: 'lowerBuoyancyTest.valveResetInches', label: 'Lower Buoyancy Valve Reset (Inches)', type: 'text' },
    ],
  },
  {
    group: 'FLOOR TEST',
    fields: [
      { id: 'floorTest.startOn', label: 'Floor Start On', type: 'text' },
      { id: 'floorTest.pressureWaterInches', label: 'Floor Pr. Water (Inches)', type: 'text' },
      { id: 'floorTest.timeOff', label: 'Floor Time Off', type: 'text' },
      { id: 'floorTest.pressureWaterInches2', label: 'Floor Pr. Water (Inches 2)', type: 'text' },
      { id: 'floorTest.valveResetInches', label: 'Floor Valve Reset (Inches)', type: 'text' },
    ],
  },
  {
    group: 'ROOM TEMP TEST',
    fields: [
      { id: 'roomTempTest.startOn', label: 'Room Temp Start On', type: 'text' },
      { id: 'roomTempTest.pressureWaterInches', label: 'Room Temp Pr. Water (Inches)', type: 'text' },
      { id: 'roomTempTest.timeOff', label: 'Room Temp Time Off', type: 'text' },
      { id: 'roomTempTest.pressureWaterInches2', label: 'Room Temp Pr. Water (Inches 2)', type: 'text' },
      { id: 'roomTempTest.valveResetInches', label: 'Room Temp Valve Reset (Inches)', type: 'text' },
    ],
  },
  {
    group: 'TEST RESULTS',
    fields: [
      { id: 'testResults.upperBuoyancy', label: 'Upper Buoyancy', type: 'text' },
      { id: 'testResults.gasInflation', label: 'Gas Inflation', type: 'text' },
      { id: 'testResults.lowerBuoyancy', label: 'Lower Buoyancy', type: 'text' },
      { id: 'testResults.nap', label: 'N.A.P.', type: 'text' },
      { id: 'testResults.floor', label: 'Floor', type: 'text' },
      { id: 'testResults.floorSeam', label: 'Floor Seam', type: 'text' },
      { id: 'testResults.roomTemperature', label: 'Room Temperature', type: 'text' },
      { id: 'testResults.dlOverload', label: 'D/L Overload', type: 'text' },
    ],
  },
  {
    group: 'OTHER INFO',
    fields: [
      { id: 'otherInfo.lengthOfPainter', label: 'Length of Painter', type: 'text' },
      { id: 'otherInfo.maxStowage', label: 'Max Stowage', type: 'text' },
      { id: 'otherInfo.emergencyPackType', label: 'Emergency Pack Type', type: 'text' },
      { id: 'otherInfo.solas', label: 'SOLAS " "', type: 'text' },
    ],
  },
  {
    group: 'CO2 Cylinders',
    fields: [
      { id: 'co2Cylinders.quantity', label: 'CO2 Cylinders (Qty)', type: 'number' },
      { id: 'co2Cylinders.serialNo', label: 'CO2 Cylinder Serial No.', type: 'text' },
      { id: 'co2Cylinders.hydroTestDate', label: 'Hydro Test Date', type: 'date' },
      { id: 'co2Cylinders.actualWeightKg', label: 'Actual Weight (Kg)', type: 'number' },
      { id: 'co2Cylinders.writtenGrossWeightKg', label: 'Written Gross Weight (Kg)', type: 'number' },
      { id: 'co2Cylinders.tareWeightKg', label: 'Tare Weight (Kg)', type: 'number' },
      { id: 'co2Cylinders.co2WeightKg', label: 'CO2 Weight (Kg)', type: 'number' },
      { id: 'co2Cylinders.contentN2Kg', label: 'Content N2 (Kg)', type: 'number' },
    ],
  },
  {
    group: 'Final Certification',
    fields: [
      { id: 'finalCertification.generalComments', label: 'General Comments', type: 'textarea' },
      { id: 'finalCertification.competentPersonName', label: 'Competent Person Name', type: 'text' },
      { id: 'finalCertification.competentPersonDesignationAuthorization', label: 'Competent Person Designation / Authorization', type: 'text' },
      { id: 'finalCertification.companyName', label: 'Company Name', type: 'text' },
    ],
  },
  {
    group: 'Sea Cells',
    fields: [
      { id: 'seaCells.status', label: 'Sea Cells Status', type: 'text' },
      { id: 'seaCells.make', label: 'Sea Cells Make', type: 'text' },
      { id: 'seaCells.expiry', label: 'Sea Cells Expiry', type: 'date' },
    ],
  },
];
